### PR TITLE
feat(Paging): Added support for @odata.maxpagesize and @odata.nextLink

### PR DESCRIPTION
**Pull request by geerzo**
Added support for the OData features of:
 - Max Page Size - determines how many records to bring back with a page
 - Next Page - supports getting the next page of records based on Max Page Size

There is one major thing I'm not happy with and it was the hack I had to put in to get the test to pass. Some issue with how the HttpHeaders use lazy updating kept causing the tests to fail unless both sides were fully resolved. I'd love to see that get fixed...or just drop the test maybe?

### CODE REVIEW

**Comment by StefH** [comment]
Thanks I will take a look.

Btw I just started upgrading some packages and used npm audit fix to fix some dependencies. Also noticed that the post to odata failed.

In order to minimize merge conflicts, I will first focus on your PR and unit tests. Aftet that I will add my changes.

Its really a coincidence that I started an hour ago on my update....

**Comment by geerzo** [comment]
I tried to get it done yesterday but I ran into a problem with NPM after merging in the latest changes from your master. I don't think the current lock file works properly. Mine should fix those issues.

Let me know if you find anything odd and I can go back and fix if needed.

**Comment by StefH** [comment]
I did merge the code and refactored a little bit and pushed to this branch.

Still want to find get some details on that `hack`

**Comment by geerzo** [comment]
Let me know what you find. I'm sure there is a better way to solve the problem but I'm not sure what it is.

**Comment by StefH** [comment]
@geerzo I was able to fix the testing by using a custom jasmine HttpOptionsMatcher (looks like the HttpHeadersMatcher)

Now the tests all run fine.

**Comment by geerzo** [comment]
Awesome. I'll take a look when you push your commits

**Comment by StefH** [comment]
All commits are pushed now;  you can review the changes.

**Comment by geerzo** [comment]
Looks good to me. Tests pass and implementation works.

**Pull request merged**
