### PR TITLE
Requesting an Individual Property

### PR DESCRIPTION
**Pull request by pleshakovalexander**
https://www.odata.org/getting-started/basic-tutorial/

### CODE REVIEW

**Review by StefH — CHANGES_REQUESTED** [review]
@pleshakovalexander 
Thank you for the PR.

Can you please format the .ts files with the same number of spaces as before?

**Comment by pleshakovalexander** [comment]
@StefH what formating extension are you using?

**Comment by StefH** [comment]
Just default right click 'format document', with ESLINT?

**Comment by pleshakovalexander** [comment]
@StefH done

**Review by StefH — APPROVED** [review]
ok

**Pull request merged**
