### PR TITLE
fix(angular): Upgrade to Angular 8 (#82)

### LINKED ISSUE #82: Add support for Angular 8
After upgrading project to Angular 8 I see the following peer dependencies warnings:
```
npm WARN angular-odata-es5@0.8.1 requires a peer of @angular/common@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-odata-es5@0.8.1 requires a peer of @angular/core@>=7.0.0 <8.0.0 but none is installed. You must install peer dependencies yourself.
```

Could you please upgrade the library to support Angular 8?

### PR DESCRIPTION
**Pull request by shvydky**
I have updated packages.json to work with Angular 8. Several other dependencies also updated. These changes should fix #82.

### CODE REVIEW

**Comment by StefH** [comment]
There was already a PR it seems.

Which one is most correct / most recent?

**Comment by shvydky** [comment]
I have made only the necessary changes and don't touch all other dependencies:

1. All @angular.* modules except for @angular/http were updated from 7.1.4 to 8.2.6
1. Dependency on @angular/http was removed as this module is deprecated in Angular 8 (actually in Angular 4 but removed only in Angular 8)
1. Updated several development dependencies to get rid of extra build warnings:
- codelyzer 4.5.0 --> 5.1.0
- rxjs 6.3.0 --> 6.5.3
- typescript 3.1.1 --> 3.5.1
- zone.j 0.8.26 --> 0.9.1

The pull request #81 also should work but it upgrades some extra dependencies. To be honest, I didn't see this PR before you wrote to me.

**Comment by StefH** [comment]
Ok.

Question: does the demo still work when upgrading to v 8?

**Comment by shvydky** [comment]
Yes, the demo works after my upgrade.

**Pull request merged**
