### PR TITLE
refactor(all): Change Http to HttpClient

### PR DESCRIPTION
**Pull request by Sir-J**
Change Http to HttpClient

### CODE REVIEW

**Review by StefH — CHANGES_REQUESTED** [review]
The unit tests fail : 17 FAILED, can you take a look and try to fix this?

**Comment by StefH** [comment]
Can you take a look at the failing unit-tests ?

**Comment by Sir-J** [comment]
I fixed all tests

**Comment by Sir-J** [comment]
When do you accept PR?

**Review by StefH — APPROVED** [review]

**Comment by StefH** [comment]
I will do this weekend.

**Comment by StefH** [comment]
There are several issues, I;m currently looking into these.

**Pull request merged**
