### PR TITLE
fix(utils): fix single quote escaping

### LINKED ISSUE #35: Strings with more than one single quote are not completely escaped
The current implementation only escapes the first single quote.

### PR DESCRIPTION
**Pull request by markwaddle**
Fixes string escaping to account for more than one single quote in a string

fix #35

### CODE REVIEW

**Review by StefH — COMMENTED** [review]
Shouldnt we actually use code like https://github.com/joliss/js-string-escape/blob/master/index.js ?

**Comment by StefH** [comment]
Can you take a look at my comment?

**Comment by markwaddle** [comment]
i think you are right about that. it needs all of those, except for the double quote escaping

**Comment by markwaddle** [comment]
after further consideration, i believe we only need to escape single quotes. the single quotes are the boundary characters for a string. the other characters are allowed, as they are simply characters, and will be encoded in the URL, which makes them a single line for transmission in the request.

**Pull request merged**
